// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Config struct {
	Beep             *bool `json:"beep"`
	Loop             *bool `json:"loop"`
	AllowOverride    *bool `json:"allowOverride"`
	Volume           *int  `json:"volume"`
	PlayStartupSound *bool `json:"playStartupSound"`
}

type ConfigInput struct {
	Beep             *bool `json:"beep"`
	Loop             *bool `json:"loop"`
	AllowOverride    *bool `json:"allowOverride"`
	Volume           *int  `json:"volume"`
	PlayStartupSound *bool `json:"playStartupSound"`
}

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewSong struct {
	ID   *string `json:"id"`
	Rfid *string `json:"rfid"`
	URL  string  `json:"url"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Song struct {
	ID       string  `json:"id"`
	Rfid     *string `json:"rfid"`
	Title    *string `json:"title"`
	URL      string  `json:"url"`
	Thumb    *string `json:"thumb"`
	FilePath *string `json:"filePath"`
}

type SongInput struct {
	ID  string  `json:"id"`
	URL *string `json:"url"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
