// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewSong struct {
	ID   *string `json:"id"`
	Rfid *string `json:"rfid"`
	URL  string  `json:"url"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Song struct {
	ID   string  `json:"id"`
	Rfid *string `json:"rfid"`
	URL  string  `json:"url"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
