https: true
rfid-enabled: true
host: :8000



startup_sound: true
startup_file: song_files/windows-xp-startup.mp3
beep: true

# should be in player
loop: false
volume: 100
restart: false # allow restart cong currently playing by playing again. note: override still applies
allow_override: true # allow start new song if already playing
