allow_override: true
beep: true
host: :8000
https: true
localtunnel:
    enabled: false
log: level:1
player:
    loop: false
    song_root: song_files
    thumb_root: thumb_files
    volume: "100"
restart: false
rfid-enabled: true
startup:
    file: sounds/windows-xp-startup.mp3
    play: true